name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  main_job:
    name: QA tests
    runs-on: ubuntu-latest
    env:
      PHP_EXTENSIONS: mbstring, xml, mysql, gd, opcache, json, zlib
      PHP_VERSION: '8.0'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          extensions: ${{ env.PHP_EXTENSIONS }}
          coverage: none
          tools: composer:v2
          ini-values: opcache.enable_cli=1,display_errors=true,error_reporting=E_ALL

      - name: Checkout Drupal
        uses: actions/checkout@v3
        with:
          repository: drupal/drupal
          ref: 9.3.13

      - name: Install Drupal dependencies
        run: composer --no-interaction install

      - name: Install phpstan and its extensions
        run: composer --no-interaction require phpstan/phpstan

      - name: Static code analysis
        run: ./vendor/bin/phpstan -vvv analyze ./core/modules/language/src/Entity
